import arcade

WINDOW_WIDTH = 580
WINDOW_HEIGHT = 700
WINDOW_CENTER = WINDOW_WIDTH / 2
START_LIVES = 3
PAUSED = 0
IN_PLAY = 1
GAME_OVER = 2
END_OF_LEVEL_DELAY = 150
GRID_WIDTH = 20
FRAME_REFRESH = 60
DISPLAY_FRUIT = FRAME_REFRESH * 7
CHASE_TIMER = FRAME_REFRESH * 20
SCATTER_TIMER = FRAME_REFRESH * 10
FRIGHT_TIMER = FRAME_REFRESH * 10
CATCH_TIMER = FRAME_REFRESH * 3
NEW_LIFE_TIMER = FRAME_REFRESH * 3
DELAY = FRAME_REFRESH
NEW_LIFE_INTERVAL = 10000
HOLD = 0
LEFT = 1
RIGHT = 2
UP = 3
DOWN = 4

WHITE = arcade.color.WHITE
GREEN = arcade.color.GREEN
AQUA = arcade.color.AQUA
RED = arcade.color.RED
YELLOW = arcade.color.YELLOW

SCORE_FONT_SIZE = 12
INST_FONT_SIZE = 18
INFO_FONT_SIZE = 16
HEADING_FONT_SIZE = 30
